<?php
$this->title = "My Albums";
$this->headTitle($this->title);
?>

<table class="table table-bordered table-condensed table-striped">
    <tr>
	<th>Title</th>
	<th>Artist</th>
	<th colspan="2">Actions </th>
    </tr>
    <?php foreach ($this->albums as $album) : ?>
        <tr>
    	<td><?php echo $this->escape($album->title); ?></td>
    	<td><?php echo $this->escape($album->artist); ?></td>
    	<td>
    	    <a href="<?php echo $this->url(array('controller' => 'album','action' => 'edit', 'id' => $album->id));?>">Edit</a>
	</td>
	<td>
	    <a href="<?php echo $this->url(array('controller' => 'album','action' => 'delete', 'id' => $album->id));?>">Delete</a>
    	</td>
        </tr>
    <?php endforeach; ?>
</table>

 <a class="btn btn-primary"  href=" <?php echo $this->url(array('controller' => 'album', 'action' => 'add')); ?>">Add new album</a>


