<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Zend Framework Tutorial');
echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
	<?php echo $this->headMeta(); ?>
	<?php echo $this->headTitle(); ?>
	<?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/bootstrap-responsive.min.css'); ?>
	<?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/bootstrap.min.css'); ?>
	<?php echo $this->headScript()->appendFile($this->baseUrl() . '/js/bootstrap.js'); ?>

    </head>
    <body>
	<div class="container">
	    <div id="content">
		<?php echo $this->layout()->content; ?>
	    </div>
	</div>
    </body>
</html>